# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54186d0de0801fc3d58cd427d030ab78ef9f8599ef2579fee632f1070eed3c1c7f4da43eac53a501f5070725e92b88c603935d0da346ca598acfd0dbe60e9458

test:
  secret_key_base: 7073423f9c2008b06ec7c427fe80be4494e40b295e36b3e23ec023495b8b07247b4c7628791e77a9b9288541edcf1b5f88a6a3ef18e21d8cfa1f933a3e7fc50d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
